# Generated by Django 4.1.5 on 2023-01-20 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.PositiveBigIntegerField()),
                ("balance_achieve", models.PositiveBigIntegerField()),
                ("code", models.CharField(max_length=50, unique=True)),
                ("enable", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "balance_bank_balance",
            },
        ),
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.CharField(blank=True, max_length=255, null=True)),
                ("balance_achieve", models.PositiveBigIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "balance_user_balance",
            },
        ),
        migrations.CreateModel(
            name="UserBalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance_before", models.PositiveBigIntegerField()),
                ("balance_after", models.PositiveBigIntegerField()),
                ("activity", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("kredit", "Kredit")],
                        max_length=50,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="balance.userbalance",
                    ),
                ),
            ],
            options={
                "db_table": "balance_user_balance_history",
            },
        ),
        migrations.CreateModel(
            name="BankBalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance_before", models.PositiveBigIntegerField()),
                ("balance_after", models.PositiveBigIntegerField()),
                ("activity", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("kredit", "Kredit")],
                        max_length=50,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="balance.bankbalance",
                    ),
                ),
            ],
            options={
                "db_table": "balance_bank_balance_history",
            },
        ),
        migrations.AddField(
            model_name="bankbalance",
            name="user_balance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_balance",
                to="balance.userbalance",
            ),
        ),
    ]
